---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
Only need to install packages once 
```{r}

# We can write R code here!!!!!
library(devtools)   # install.packages("devtools")
library(tidyverse) # install.packages("tidyverse")
library(steponeR) # install_github("jrcunning/steponeR")

```


# Import qPCR data with steponeR package

For help use "?steponeR"

```{r load_data}
# List data files
plates <- list.files(path = "Data/qPCR", pattern = ".txt", full.names = TRUE)
plates
# Read in data and calculate target ratios
df <- steponeR(files = plates, 
               delim = "\t", 
               target.ratios = c("C.Orb", "D.Orb", "A.Orb", "B.Orb"), 
               fluor.norm = list(C = 2.234, D = 1, Orb = 1, A = 1, B = 1),
               copy.number = list(C = 20, D = 3, Orb = 1, A = 1, B = 1),
               ploidy = list(C = 1, D = 1, Orb = 2, A = 1, B = 1),
               extract = list(C = 0.813, D = 0.813, Orb = 0.982, A = 0.813, B = 0.813))
qpcr <- df$result
# View data
head(qpcr)
View(qpcr)
# Show samples that didn't work
fails <- qpcr %>%
  filter(is.na(C.Orb) & is.na(D.Orb) & is.na(A.Orb) & is.na(B.Orb))

# Filter out samples that didn't amplify
qpcr_good <- qpcr %>%
  filter(!(is.na(C.Orb) & is.na(D.Orb) & is.na(A.Orb) & is.na(B.Orb)))

# Convert ratios that are NaN to zero
qpcr_good <- qpcr_good %>%
  mutate(A.Orb = ifelse(is.na(A.Orb), 0, A.Orb),
         B.Orb = ifelse(is.na(B.Orb), 0, B.Orb),
         C.Orb = ifelse(is.na(C.Orb), 0, C.Orb),
         D.Orb = ifelse(is.na(D.Orb), 0, D.Orb))

qpcr_good <- qpcr_good %>%
  mutate(dom_sym = case_when(B.Orb > C.Orb & B.Orb > D.Orb & B.Orb > A.Orb ~ "B",
                             C.Orb > B.Orb & C.Orb > D.Orb & C.Orb > A.Orb ~ "C",
                             D.Orb > B.Orb & D.Orb > C.Orb & D.Orb > A.Orb ~ "D",
                             A.Orb > B.Orb & A.Orb > C.Orb & A.Orb > D.Orb ~ "A"))

table(qpcr_good$dom_sym)
```


# Visualizing Symbiont Communities 
```{r}
qpcr_good %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb) %>%
  gather(key = "sym", value = "value", -Sample.Name) %>%
  ggplot(aes(x = Sample.Name, y = value, fill = sym)) +
  geom_bar(stat = "identity", position = "fill")
  
```
