---
output: html_document
editor_options: 
  chunk_output_type: console
---
title: "Sym_temp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)   # install.packages("devtools")
library(steponeR) # install_github("jrcunning/steponeR")
```


```{r}
# List Sandy Cay symbiodinium data files
plates <- list.files(path = "Data/qPCR", pattern = ".txt", full.names = TRUE)
plates
# Read in data and calculate target ratios
df <- steponeR(files = plates, 
               delim = "\t", 
               target.ratios = c("C.Orb", "D.Orb", "A.Orb", "B.Orb"), 
               fluor.norm = list(C = 2.234, D = 1, Orb = 1, A = 1, B = 1),
               copy.number = list(C = 20, D = 3, Orb = 1, A = 1, B = 1),
               ploidy = list(C = 1, D = 1, Orb = 2, A = 1, B = 1),
               extract = list(C = 0.813, D = 0.813, Orb = 0.982, A = 0.813, B = 0.813))
qpcr <- df$result

# View data
head(qpcr)
```

```{r}
library(tidyverse) # install.packages("tidyverse")
```

```{r}
# Change NA Orb values to 27
qpcr <- qpcr %>% 
  mutate(Orb.CT.mean = ifelse(is.na(Orb.CT.mean), 27, Orb.CT.mean))

# Show samples that didn't work
fails <- qpcr %>%
  filter(is.na(C.Orb) & is.na(D.Orb) & is.na(A.Orb) & is.na(B.Orb))

# Filter out samples that didn't amplify and positive controls
qpcr_good <- qpcr %>%
  filter(!(is.na(C.Orb) & is.na(D.Orb) & is.na(A.Orb) & is.na(B.Orb))) %>%
  filter(Sample.Name != "PTC") %>%
  filter(Sample.Name != "NTC")

# Convert ratios that are NaN to zero
qpcr_good <- qpcr_good %>%
  mutate(A.Orb = ifelse(is.na(A.Orb), 0, A.Orb),
         B.Orb = ifelse(is.na(B.Orb), 0, B.Orb),
         C.Orb = ifelse(is.na(C.Orb), 0, C.Orb),
         D.Orb = ifelse(is.na(D.Orb), 0, D.Orb))


# Assigning Dominant Symbiont based on Ratio
qpcr_good <- qpcr_good %>%
  mutate(dom_sym = case_when(B.Orb > C.Orb & B.Orb > D.Orb & B.Orb > A.Orb ~ "Breviolum",
                             C.Orb > B.Orb & C.Orb > D.Orb & C.Orb > A.Orb ~ "Cladocopium",
                             D.Orb > B.Orb & D.Orb > C.Orb & D.Orb > A.Orb ~ "Durusdinium",
                             A.Orb > B.Orb & A.Orb > C.Orb & A.Orb > D.Orb ~ "Symbiodinium")) %>%
  mutate(dom_sym = factor(dom_sym))
```


#Filtering out "bad" data/replicates
```{r}
#Determing which samples have 2 replicates in the data set
dupes <- qpcr_good %>%
  count(Sample.Name) %>%
  filter(n > 1)

#Gathering the full data for samples with 2 replicates
qpcr_dupes <- qpcr_good %>%
  filter(Sample.Name %in% dupes$Sample.Name) %>%
  arrange(Sample.Name)

#filtering out data with only 1 technical replicate
qpcr_dupes_f1 <- qpcr_dupes %>%
  group_by(Sample.Name) %>%
  filter(A.reps != 1, B.reps != 1, C.reps != 1, D.reps != 1) %>%
  ungroup()

# tyring to get standard deviation averages by row to choose "better" of multiple samples 
qpcr_dupes_f2 <- qpcr_dupes_f1 %>%
  rowwise() %>%
  mutate(avg_sd = mean(c(A.CT.sd, B.CT.sd, C.CT.sd, D.CT.sd), na.rm = TRUE)) %>%
  group_by(Sample.Name) %>%
  filter(avg_sd == avg_sd[which.min(avg_sd)])

qpcr_good <- qpcr_good %>%
  filter(!Sample.Name %in% dupes$Sample.Name) %>%
  bind_rows(qpcr_dupes_f2)

qpcr_still_bad <- qpcr_good %>%
  filter(A.reps == 1| B.reps == 1| C.reps == 1| D.reps == 1| Orb.reps == 1) %>%
  select(Sample.Name, File.Name, A.reps, B.reps, C.reps, D.reps, Orb.reps)
  

#SC029 is missing, needs to be looked at in quant or rerun
setdiff(qpcr_dupes$Sample.Name, qpcr_dupes_f2$Sample.Name)


setdiff(qpcr$Sample.Name, qpcr_good$Sample.Name)



  
```

```{r}
#visualizing Symbiont Communities 
sym_commun <- qpcr_good %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb) %>%
  mutate(Symbiodinium = case_when(A.Orb > 0 ~ A.Orb),
         Breviolum = case_when(B.Orb > 0 ~ B.Orb),
         Cladocopium = case_when(C.Orb > 0 ~ C.Orb),
         Durusdinium = case_when(D.Orb > 0 ~ D.Orb)) %>%
  select(Sample.Name, Symbiodinium, Breviolum, Cladocopium, Durusdinium) %>%
  gather(key = "sym", value = "value", -Sample.Name) %>%
  mutate(site = factor(str_sub(Sample.Name, start = 1, end = 2))) 
  
sites <- as_labeller(c(SC = "Sandy Cay", MR = "Mermaid Reef"))

ggplot(sym_commun, aes(x = Sample.Name, y = value, fill = sym)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(~site, scales = "free", labeller = sites) +
  xlab("Sample") +
  ylab("Proportion of Symbionts in Coral") +
  labs(fill = "") +
  scale_fill_manual(values = c( "#7CAE00", "#00BFC4", "#C77CFF", "#F8766D")) +
  theme_minimal() +
  theme(axis.title.x = element_text(size = 30),
        axis.title.y = element_text(size = 30),
        axis.text.x = element_text(size = 30, color = "transparent", margin = margin(t = -20)),
        axis.text.y = element_text(size = 30, color = "black", margin = margin(l = 30)),
        panel.background = element_rect(color ="black"),
        panel.border = element_rect(color = "black", fill = NA, size = 1.5),
        legend.text = element_text(size = 25, face = "italic"),
        legend.position = "bottom")

ggsave(filename = "figures/symiont_comp.png", width = 400, height = 300, units = "mm")


```

```{r}
# Taking dominant symbiont and sample name data from qpcr_good data frame 
dom_sym_ratio <- qpcr_good %>%
  select(Sample.Name, dom_sym)
```

```{r}
#Uses gather function to restructure data frame from wide to long
graph_good <- qpcr_good %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb, dom_sym) %>%
  gather(key = "sym", value = "value", -Sample.Name, -dom_sym)
```

```{r}
#import depth data 
#library(readr)
sample_data <- readxl::read_xlsx("Data/Temperature/sample_data.xlsx")
#View(depth)
```

```{r}
# add depth to qpcr_good data frame 
#depth_sym <- merge(graph_good, depth, by = "Sample.Name")
depth_dom_sym <- sample_data %>%
  select(tube_label, colony_depth_m, site) %>%
  rename(Sample.Name = tube_label, depth = colony_depth_m) %>%
  right_join(graph_good)
```


```{r}
# Condensing dominant symbiont values to one per sample name 
depth_dom_sym <- depth_dom_sym %>%
  distinct(Sample.Name, depth, dom_sym, site)
```

```{r}
#Form data table to separate by site 
depth_int_ncol<- depth_dom_sym %>%
  filter(depth != "NA") %>%
  mutate(depth_int = cut(depth, breaks = 4)) %>%
  group_by(depth_int, dom_sym, site) %>%
  summarise(ncol = n()) %>%
  mutate(depth = case_when(grepl("1.19,2.8", depth_int) ~ "(1.2 - 2.8)" ,
                           grepl("2.8,4.4", depth_int) ~ "(2.8 - 4.4)", 
                           grepl("4.4,6", depth_int) ~ "(4.4 - 6.0)",
                           grepl("6,7.61", depth_int) ~ "(6.0 - 7.6)"))

reefs <- as_labeller(c(sandy_cay = "Sandy Cay", mermaid_reef = "Mermaid Reef"))


#Plot depth vs percent of sym dominance by site
ggplot(depth_int_ncol, aes(x = as.factor(depth), y = ncol, fill = dom_sym)) +
  facet_wrap(~site, labeller = reefs) +
  geom_bar(stat = "identity", position = "fill", size =20) +
  scale_y_continuous(expand = c(0,0)) +
  xlab("Depth (m)") +
  ylab("% of Corals Housing Symbiont") +
  theme_bw() +
  theme(axis.text.y = element_text(size = 30, color = "black", margin = margin(l = 40)),
        axis.text.x = element_text(size = 23, color = "black", margin = margin(b = 20)),
        axis.title = element_text(size = 30), 
        legend.title = element_text(size = 25),
        legend.text = element_text(size = 25, face = "italic"),
        legend.position = "bottom",
        strip.text.x = element_text(size = 25)) +
  guides(fill=guide_legend(title="")) +
  scale_fill_manual(values = c( "#7CAE00", "#00BFC4", "#C77CFF", "#F8766D"))

ggsave(filename = "figures/depth_symbionts.png", width = 380, height = 400, units = "mm")

position = position_dodge(width=0.5)




```

```{r}
depth_dom_sym %>%
  filter(depth != "NA") %>%
  ggplot(aes(x = site, y = -(depth), fill = site)) +
  geom_violin(width = 1.5, show.legend = FALSE, color = "transparent", alpha = 0.7) +
  scale_fill_manual(values=c("#52ECD2", "#1141C5")) + 
  geom_boxplot(width = 0.14, show.legend = FALSE, fill = "white", lwd = 1) +
  ylab(label = "Depth (m)") +
  xlab(label = "") +
  scale_x_discrete(labels = c("Mermaid Reef", "Sandy Cay")) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 35, color = "black"),
        axis.text.y = element_text(size = 35, color = "black", margin =margin(l = 30)),
        axis.title.y = element_text(size = 35),
        axis.line = element_line(color = "white"),
        panel.grid.major.y = element_line(color = "gray"),
        panel.grid.major.x = element_line(color = "gray"),
        panel.grid.minor = element_line(color = "gray"),
        panel.grid.minor.x = element_line(color = "gray")) 

ggsave(filename = "figures/depth_violin.png", width = 300, height = 300, units = "mm")

metrics<- depth_dom_sym %>%
  group_by(site) %>%
  summarize(
    mean = mean(depth, na.rm = TRUE),
    min = min(depth, na.rm = TRUE),
    max = max(depth, na.rm = TRUE),
    median = median(depth, na.rm = TRUE))
  


   
```

```{r}
m <- depth_dom_sym %>%
  select(Sample.Name, depth, site) %>%
  right_join(qpcr_good) %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb, site, depth) %>%
  mutate(Symbiodinium = case_when(A.Orb > 0 ~ 1),
         Breviolum = case_when(B.Orb > 0 ~ 1),
         Cladocopium = case_when(C.Orb > 0 ~ 1),
         Durisdinium = case_when(D.Orb > 0 ~ 1)) %>%
  select(Sample.Name, Symbiodinium, Breviolum, Cladocopium, Durisdinium, site, depth) %>%
  mutate(Symbiodinium = ifelse(is.na(Symbiodinium), 0, Symbiodinium),
         Breviolum = ifelse(is.na(Breviolum), 0, Breviolum),
         Cladocopium = ifelse(is.na(Cladocopium), 0, Cladocopium),
         Durisdinium = ifelse(is.na(Durisdinium), 0, Durisdinium)) %>%
  gather(key = "sym", value = "value", -Sample.Name, -site, -depth) %>%
  filter(value != 0) %>%
  mutate(depth_int = cut(depth, breaks = 4)) %>%
  group_by(depth_int, sym, site) %>%
  summarise(ncol = n()) 

sc_sym <- m %>%
  filter(site != "mermaid_reef")



ggplot(sc_sym, aes(x = depth_int, y = ncol, fill = sym)) +
  facet_wrap(~site, labeller = reefs) +
  geom_bar(stat = "identity", position = position_dodge()) +
  xlab("Depth (m)") +
  ylab("Number of Corals Housing Symbiont") +
  guides(fill=guide_legend(title="Symbiont")) +
  scale_fill_manual(values = c( "#7CAE00", "#00BFC4", "#C77CFF", "#F8766D")) 

 
  
 
  
  
  
  
  
  
   
```













```{r}
# Prevalence of each symbiodinium overall
prev_sym <- sample_data %>%
  rename(Sample.Name = tube_label, depth = colony_depth_m) %>%
  mutate(Site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  select(Sample.Name, Site) %>%
  filter(Site != "MR") %>%
  merge(qpcr_good, by = "Sample.Name") %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb, Site) %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb) %>%
  rename(Symbiodinium = A.Orb, Breviolum = B.Orb, Cladocopium = C.Orb, Durusdinium = D.Orb) %>%
  gather(key = "sym", value = "value", -Sample.Name)

sym_yes <- prev_sym %>%
  filter(value > 0)

#Finding the percentage of each symbiont 
sym_yes %>%
  count(vars = sym) %>%
  mutate(prev = n/30 * 100) %>%
  ggplot(aes(x = vars, y = prev, fill = vars)) +
  geom_bar(stat = "identity", postion = "fill") +
  scale_y_continuous(expand = c(0, 0)) +
  xlab("") +
  ylab("% of Corals Housing Symbiont") +
  theme_bw() +
  theme(axis.text.y = element_text(size = 12, color = "black", margin =margin(l = 20)),
        axis.text.x = element_text(size = 14, color = "black", face = "italic"),
        axis.title = element_text(size = 14),
        panel.grid.major.y = element_line(color = "gray"),
        panel.background = element_rect(color = "transparent")) +
  scale_fill_manual(values = c( "#7CAE00", "#00BFC4", "#C77CFF", "#F8766D")) 

ggsave(filename = "figures/prev_SC.png", width = 350, height = 175, units = "mm")

```

```{r}
prev_sym_MR <- sample_data %>%
  rename(Sample.Name = tube_label, depth = colony_depth_m) %>%
  mutate(Site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  select(Sample.Name, Site) %>%
  merge(qpcr_good, by = "Sample.Name") %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb, Site) %>%
  filter(Site == "MR") %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb) %>%
  rename(Symbiodinium = A.Orb, Breviolum = B.Orb, Cladocopium = C.Orb, Durusdinium = D.Orb) %>%
  gather(key = "sym", value = "value", -Sample.Name) %>%
  select(sym, value) 


prev_sym_MR %>%
  count(vars = sym) %>%
  mutate(prev = n/40 * 100) %>%
  ggplot(aes(x = vars, y = prev, fill = vars)) +
  geom_bar(stat = "identity", postion = "fill", show.legend = FALSE) +
  scale_y_continuous(expand = c(0,0)) +
  xlab("") +
  ylab("% of Corals Housing Symbiont") +
  theme_bw() +
  theme(axis.text.y = element_text(size = 12, color = "black", margin =margin(l = 20)),
        axis.text.x = element_text(size = 14, color = "black", face = "italic"),
        axis.title = element_text(size = 14), 
        panel.grid.major.y = element_line(color = "gray"),
        panel.background = element_rect(color = "transparent")) +
  scale_fill_manual(values = c( "#ffffff00", "#ffffff00", "#C77CFF", "#ffffff00"))

ggsave(filename = "figures/prev_MR.png", width = 350, height = 175, units = "mm")
```








#Prevalence of Symbiont Combinations at SC 
```{r}
sym_combos <- sample_data %>%
  rename(Sample.Name = tube_label, depth = colony_depth_m) %>%
  mutate(Site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  select(Sample.Name, Site) %>%
  merge(qpcr_good, by = "Sample.Name") %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb, Site) %>%
  filter(Site == "SC") %>%
  mutate(symbiont = case_when(A.Orb > 0 & B.Orb > 0 & C.Orb == 0 & D.Orb == 0 ~ "AB",
                             A.Orb > 0 & B.Orb == 0 & C.Orb > 0 & D.Orb == 0 ~ "AC",
                             A.Orb > 0 & D.Orb > 0 & B.Orb == 0 & C.Orb == 0 ~ "AD",
                             A.Orb == 0 & B.Orb > 0 & C.Orb > 0 & D.Orb == 0 ~ "BC",
                             A.Orb == 0 & B.Orb > 0 & C.Orb == 0 & D.Orb > 0 ~ "BD",
                             A.Orb == 0 & B.Orb == 0 & C.Orb > 0 & D.Orb > 0 ~ "CD",
                             A.Orb > 0 & B.Orb > 0 & C.Orb > 0 & D.Orb > 0 ~ "ABCD",
                             A.Orb > 0 & B.Orb > 0 & C.Orb > 0 & D.Orb == 0 ~ "ABC",
                             A.Orb > 0 & B.Orb > 0 & D.Orb > 0 & C.Orb == 0 ~ "ABD",
                             A.Orb == 0 & B.Orb > 0 & C.Orb > 0 & D.Orb > 0 ~ "BCD",
                             A.Orb > 0 & B.Orb == 0 & C.Orb > 0 & D.Orb > 0 ~ "ACD",
                             A.Orb == 0 & B.Orb > 0 & C.Orb > 0 & D.Orb > 0 ~ "BCD",
                             A.Orb > 0 & B.Orb == 0 & C.Orb == 0 & D.Orb == 0 ~ "A",
                             B.Orb > 0 & A.Orb == 0 & C.Orb == 0 & D.Orb == 0 ~ "B",
                             C.Orb > 0 & A.Orb == 0 & B.Orb == 0 & D.Orb == 0 ~ "C",
                             D.Orb > 0 & A.Orb == 0 & B.Orb == 0 & C.Orb == 0 ~ "D")) %>%
  mutate(symbiont = factor(symbiont))

sym_combos_graph <- sym_combos %>%
  select(Sample.Name, symbiont) %>%
  count(vars = symbiont) %>%
  mutate(prev = n) %>%
  select(vars, prev) %>%
  ggplot(aes(x = vars, y = prev, fill = vars)) +
  geom_col()
```


```{r}
# Network Analysis of symbionts at SC

library(igraph) #install.packages("igraph")
library(fields)

net_data_SC <- sym_combos %>%
  mutate(total = A.Orb + B.Orb + C.Orb + D.Orb, 
         A.prop = A.Orb/total,
         B.prop = B.Orb/total,
         C.prop = C.Orb/total,
         D.prop = D.Orb/total) %>%
  select(Sample.Name, Symbiodinium = A.prop, Breviolum = B.prop, Cladocopium = C.prop, Durisdinium = D.prop)



edges_SC <- net_data_SC %>%
  gather(key = "Genera", value = "weight", -Sample.Name) %>%
  filter(weight != 0)


depth_SC <- depth_dom_sym %>%
  select(Sample.Name, depth, site) %>%
  filter(site == "sandy_cay") %>%
  select(Sample.Name, depth) 

verts_SC <- tibble(Sample.Name = c(net_data_SC$Sample.Name, colnames(net_data_SC)[-1])) %>%
  left_join(depth_SC) %>%
  rename(id = Sample.Name) %>%
  mutate(lab = case_when(grepl("SC", id) ~ "", grepl("um", id) ~ str_sub(id, start = 1, end = 1))) 
  
net_SC <- graph_from_data_frame(edges_SC, directed = FALSE, vertices = verts_SC)



  
  png("Figures/SC_Network.png", width = 300, height = 300, units = "mm", res = 600)
  
  set.seed(40) 
  
  plot(net_SC, edge.curved = 0, 
       edge.width = 15 * (E(net_SC)$weight)^0.5, 
       edge.color = "gray65",
       vertex.label = V(net_SC)$lab,
       vertex.label.font = 2,
       vertex.label.cex = 2.5,
       vertex.label.color = "black", 
       vertex.size = ifelse(grepl("SC", names(V(net_SC))), 10, 25),
       vertex.color = ifelse(grepl("SC", names(V(net_SC))), 
                             colorRampPalette(c("white", "black"))(100)[as.numeric(cut(V(net_SC)$depth,breaks = 100))],
                             c("#00BFC4","#C77CFF", "#F8766D", "#7CAE00")))
  
  image.plot(legend.only = TRUE, 
             zlim = range(V(net_SC)$depth, na.rm = TRUE),
             horizontal = TRUE,
             legend.shrink = 0.6,
             legend.lab = "Depth (m)",
             col = colorRampPalette(c("white", "black"))(100))
  
  
  dev.off()





```

```{r}
# Network Analysis of symbionts at MR

library(igraph) #install.packages("igraph")

net_data_MR <- qpcr_good %>%
  select(Sample.Name, A.Orb, B.Orb, C.Orb, D.Orb) %>%
  merge(depth_dom_sym) %>%
  filter(site == "mermaid_reef") %>%
  select(Sample.Name, D.Orb) %>%
  mutate(D.prop = D.Orb/D.Orb) %>%
  select(Sample.Name, D.prop)

edges_MR <- net_data_MR %>%
  gather(key = "Clade", value = "weight", -Sample.Name) %>%
  filter(weight != 0)

depth_MR <- depth_dom_sym %>%
  select(Sample.Name, depth, site) %>%
  filter(site == "mermaid_reef") %>%
  select(Sample.Name, depth)

verts_MR <- tibble(Sample.Name = c(net_data_MR$Sample.Name, colnames(net_data_MR)[-1])) %>%
  left_join(depth_MR) %>%
  rename(id = Sample.Name) %>%
  mutate(lab = case_when(grepl("SC", id) ~ "",
                         grepl(".prop", id) ~ str_sub(id, start = 1, end = 1)))

net_MR <- graph_from_data_frame(edges_MR, directed = FALSE, vertices = verts_MR)

png("Figures/MR_Network.png", width = 300, height = 300, units = "mm", res = 600)

set.seed(8)

plot(net_MR, edge.curved = 0, 
     edge.width = 10 * (E(net_MR)$weight)^0.5, 
     vertex.label = V(net_MR)$lab,
     vertex.label.font = 2,
     vertex.label.cex = 2.5,
     vertex.label.color = "black",
     vertex.size = ifelse(grepl("MR", names(V(net_MR))), 10, 30),
     vertex.color = ifelse(grepl("MR", names(V(net_MR))), 
                           colorRampPalette(c("gray94"))(100)[as.numeric(cut(V(net_MR)$depth,breaks = 100))],
                           c("#C77CFF")))

dev.off()

```























#Quality Control
```{r}
#Orb CT means at each site
qpcr_good %>%
  mutate(Site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  (aes(x = Site, y = Orb.CT.mean, fill = Site)) +
  geom_boxplot()

#Samples to Re-Extract
qual_con <- qpcr_good %>%
  select(Sample.Name, Orb.CT.mean) %>%
  filter(Orb.CT.mean > 30.0000)


#Visualizing distribution of Orb Amplification by Site and Sample 
qpcr_good %>%
  mutate(Site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  ggplot(aes(x = Sample.Name, y = Orb.CT.mean, color = Site)) +
  geom_point(size = 3) 

#Visualizing sd of symbionts to determine cutoff
sd_redo <- qpcr_good %>%
  mutate(Site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  select(Sample.Name, A.CT.sd, B.CT.sd, C.CT.sd, D.CT.sd, Site) %>%
  mutate(A.CT.sd = ifelse(is.na(A.CT.sd), 0, A.CT.sd),
         B.CT.sd = ifelse(is.na(B.CT.sd), 0, B.CT.sd),
         C.CT.sd = ifelse(is.na(C.CT.sd), 0, C.CT.sd),
         D.CT.sd = ifelse(is.na(D.CT.sd), 0, D.CT.sd)) %>%
  gather(key = sym_type, value = SD, -Sample.Name, -Site) %>%
  filter(SD != 0 & SD > 1) %>%
  ggplot(aes(x = Sample.Name, y = SD, color = Site)) +
  geom_point(size = 3)

```

```{r}
#making a histogram of MR Orb.CT.Values
histogram_MR <- qpcr_good %>%
  mutate(site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  select(Sample.Name, Orb.CT.mean, site) %>%
  filter(site != "SC")
  

hist(histogram_MR$Orb.CT.mean, 
     main = "Orb.CT.mean of Samples at MR",
     xlab = "Orb.CT.mean",
     col = "green",
     breaks = 10) 

#making a histogram of Of SC Orb.CT.Values
histogram_SC <- qpcr_good %>%
  mutate(site = str_sub(Sample.Name, start = 1, end = 2)) %>%
  select(Sample.Name, Orb.CT.mean, site) %>%
  filter(site != "MR")
  

hist(histogram_SC$Orb.CT.mean, 
     main = "Orb.CT.mean of Samples at SC",
     xlab = "Orb.CT.mean",
     col = "blue",
     breaks = 10) 

  
```