---
title: "abaco temperature analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
```

# Import data

## Mermaid Reef
```{r}
# May - October 2015
mermaid1 <- read_csv("Data/Temperature/Mermaid's_Reef_download1.csv", skip = 1) %>%
  clean_names() %>%
  mutate(time = mdy_hms(date_time_gmt_04_00),
         site = "mermaid_reef") %>%
  select(time, site, temp_c)
range(mermaid1$time)
```

```{r}
# August 2018 - January 2019
mermaid2 <- read_csv("Data/Temperature/Mermaid_Reef_8-2018_0.csv", skip = 1) %>%
  clean_names() %>%
  mutate(time = mdy_hms(date_time_gmt_04_00),
         site = "mermaid_reef") %>%
  select(time, site, temp_c) %>%
  slice(1:(n()-20))    # get rid of some wonky data at the end
range(mermaid2$time)
```

## Sandy Cay

```{r}
# May 2015 - October 2015
sandy0 <- read_csv("Data/Temperature/Sandy_Cay_Reef_-_Backreef#8_0.csv", skip = 1) %>%
  clean_names() %>%
  mutate(time = mdy_hms(date_time_gmt_04_00),
         site = "sandy_cay_reef",
         temp_c = (temp_f - 32) * 5/9) %>%
  select(time, site, temp_c) %>%
  slice(100:n())   # get rid of some wonky data at the beginning
range(sandy0$time)
```

```{r}
# October 2015 - August 2016
sandy1 <- read_csv("Data/Temperature/SANDY_Cay_Nursery.csv", skip = 1) %>%
  clean_names() %>%
  mutate(time = mdy_hms(date_time_gmt_04_00),
         site = "sandy_cay_nursery") %>%
  select(time, site, temp_c) %>%
  slice(100:n())   # get rid of some wonky data at the beginning
range(sandy1$time)
```

```{r}
# November 2017 - July 2018
sandy2 <- read_csv("Data/Temperature/Sandy_Cay_Reef_2.csv", skip = 1) %>%
  clean_names() %>%
  mutate(time = mdy_hms(date_time_gmt_05_00),
         site = "sandy_cay_reef") %>%
  select(time, site, temp_c) %>%
  slice(1:(n()-120))    # get rid of some wonky data at the end
range(sandy2$time)
```

# Merge datasets
```{r}
df <- bind_rows(mermaid1, mermaid2, sandy0, sandy1, sandy2) %>%
  mutate(monthday = format(time, format = "%m-%d"))
```


# Plot temperature over time
```{r}
ggplot(df, aes(x = time, y = temp_c, color = site)) +
  geom_line(alpha = 0.4) +
  ylim(18, 35)
```

# Plot just overlapping time period (2015)
```{r}
Q <- df %>%
  filter(time < "2015-10-15") 
  
ggplot(Q, aes(x = time, y = temp_c, color = site)) +
  geom_line(alpha = 0.3) 
```

# Plot temperature over time just by month
```{r}
ggplot(df, aes(x = monthday, y = temp_c, color = site)) +
  geom_line(alpha = 0.3)
```

# Boxplot MR vs SC
```{r}
df %>%
  filter(time < "2015-10-15") %>%
  filter(site != "sandy_cay_nursery") %>%
  select(site, temp_c) %>%
  ggplot(aes(x = site, y = temp_c, fill = site)) +
  geom_boxplot()
```

#Density plot MR vs SC
```{r}
library(ggplot2)

temp_dat <- df %>%
  filter(time < "2015-10-15") %>%
  filter(site != "sandy_cay_nursery") %>%
  select(site, temp_c) %>%
  mutate(site = factor(site, levels = c("sandy_cay_reef", "mermaid_reef")))
  



ggplot(temp_dat, aes(x = temp_c, fill = site)) +
  geom_density(alpha = 0.6, position = "identity") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 20, color = "black", margin =margin(l = 20)),
        axis.text.x = element_text(size = 20, color = "black"),
        axis.title.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        legend.text = element_text(size = 30), 
        legend.position = c(0.25, 0.6)) +
  xlab(expression("Temperature " ( degree*C))) +
  ylab(label = "Density") +
  scale_y_continuous(expand = c(0,0))  +
  scale_fill_manual(name="",
                         breaks=c("mermaid_reef", "sandy_cay_reef"),
                         labels=c("Mermaid Reef", "Sandy Cay"), values=c("#1141C5", "#52ECD2"))

ggsave(filename = "figures/temp_dens.png", width = 350, height = 175, units = "mm")
  
```

# Linear model
```{r}
library(gamm4)
```

#Table of Metric Values 
```{r}
# Mean of all Temp Data
library(gridExtra)
library(grid)

mean(df$temp_c, na.rm = TRUE)

metrics<- df %>%
  filter(time < "2015-10-15") %>%
  filter(site != "sandy_cay_nursery") %>%
  group_by(site) %>%
  summarize(
    mean = mean(temp_c, na.rm = TRUE),
    min = min(temp_c, na.rm = TRUE),
    max = max(temp_c, na.rm = TRUE),
    median = median(temp_c, na.rm = TRUE))

 
  


```


```{r}
grid.table(metrics) 
```

